# Generated by Django 3.1.7 on 2021-03-08 06:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Col',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='列名')),
                ('desc', models.CharField(default='', max_length=50, verbose_name='描述')),
                ('update_time', models.DateTimeField(default=datetime.datetime(2021, 3, 8, 14, 11, 2, 585303), verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='表名')),
                ('desc', models.CharField(default='', max_length=50, verbose_name='说明信息')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=50, verbose_name='具体值')),
                ('update', models.DateTimeField(default=datetime.datetime(2021, 3, 8, 14, 11, 2, 586304), verbose_name='更新时间')),
                ('col', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guang.col')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guang.table')),
            ],
            options={
                'verbose_name': '具体值',
                'verbose_name_plural': '具体值',
            },
        ),
        migrations.AddField(
            model_name='col',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guang.table'),
        ),
    ]
