# Generated by Django 3.1.7 on 2021-03-08 06:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='部门')),
            ],
        ),
        migrations.AlterField(
            model_name='col',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 14, 17, 54, 726803), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='value',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 14, 17, 54, 727806), verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='value',
            name='department',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='guang.department'),
            preserve_default=False,
        ),
    ]
