# Generated by Django 3.1.7 on 2021-03-10 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guang', '0002_auto_20210308_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='update_time',
            new_name='update',
        ),
        migrations.RemoveField(
            model_name='col',
            name='update_time',
        ),
        migrations.AddField(
            model_name='col',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 14, 20, 28, 113818), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='value',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 14, 20, 28, 114819), verbose_name='更新时间'),
        ),
    ]
