# Generated by Django 3.1.7 on 2021-03-10 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guang', '0003_auto_20210310_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='col',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 15, 28, 19, 890865), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='value',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 15, 28, 19, 891862), verbose_name='更新时间'),
        ),
    ]
