# Generated by Django 3.1.7 on 2021-03-10 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guang', '0004_auto_20210310_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='state',
            field=models.CharField(default='', max_length=1, verbose_name='发布状态'),
        ),
        migrations.AlterField(
            model_name='col',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 16, 30, 24, 445412), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='value',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 16, 30, 24, 446417), verbose_name='更新时间'),
        ),
    ]
