# Generated by Django 3.2.6 on 2021-08-28 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guang', '0005_auto_20210310_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0', max_length=2, verbose_name='发布状态')),
                ('name', models.CharField(default='默认类别', max_length=10, verbose_name='发布状态的名称')),
            ],
        ),
        migrations.AlterField(
            model_name='col',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 28, 16, 53, 23, 52692), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='table',
            name='state',
            field=models.CharField(default='0', max_length=2, verbose_name='发布状态'),
        ),
        migrations.AlterField(
            model_name='value',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 28, 16, 53, 23, 53691), verbose_name='更新时间'),
        ),
    ]
