# Generated by Django 3.2.6 on 2021-08-29 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guang', '0006_auto_20210828_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='默认类别', max_length=10, verbose_name='类别')),
            ],
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.AddField(
            model_name='table',
            name='tag',
            field=models.CharField(default='默认类别', max_length=10, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='col',
            name='desc',
            field=models.CharField(default='', max_length=50, verbose_name='类型定义'),
        ),
        migrations.AlterField(
            model_name='col',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 29, 11, 38, 47, 678246), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='table',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 29, 11, 38, 47, 677245), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='value',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 29, 11, 38, 47, 679246), verbose_name='更新时间'),
        ),
    ]
