# Generated by Django 3.2.6 on 2021-08-29 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guang', '0007_auto_20210829_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='c0',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c1',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c10',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c100',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c11',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c12',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c13',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c14',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c15',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c16',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c17',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c18',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c19',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c2',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c20',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c21',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c22',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c23',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c24',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c25',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c26',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c27',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c28',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c29',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c3',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c30',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c31',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c32',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c33',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c34',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c35',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c36',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c37',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c38',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c39',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c4',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c40',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c41',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c42',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c43',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c44',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c45',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c46',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c47',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c48',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c49',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c5',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c50',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c51',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c52',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c53',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c54',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c55',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c56',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c57',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c58',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c59',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c6',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c60',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c61',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c62',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c63',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c64',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c65',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c66',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c67',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c68',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c69',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c7',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c70',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c71',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c72',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c73',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c74',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c75',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c76',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c77',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c78',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c79',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c8',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c80',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c81',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c82',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c83',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c84',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c85',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c86',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c87',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c88',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c89',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c9',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c90',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c91',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c92',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c93',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c94',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c95',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c96',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c97',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c98',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AddField(
            model_name='table',
            name='c99',
            field=models.CharField(default='默认列名', max_length=20, verbose_name='列名'),
        ),
        migrations.AlterField(
            model_name='col',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 29, 21, 19, 29, 437184), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='table',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 29, 21, 19, 29, 432180), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='value',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 29, 21, 19, 29, 438185), verbose_name='更新时间'),
        ),
    ]
