# Generated by Django 3.2.6 on 2021-08-29 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guang', '0008_auto_20210829_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='col',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 29, 21, 25, 34, 243845), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='table',
            name='c0',
            field=models.IntegerField(default=0, verbose_name='列的数量'),
        ),
        migrations.AlterField(
            model_name='table',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 29, 21, 25, 34, 238842), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='value',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 29, 21, 25, 34, 244845), verbose_name='更新时间'),
        ),
    ]
