# Generated by Django 3.2.6 on 2021-08-29 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guang', '0009_auto_20210829_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='c0',
        ),
        migrations.AlterField(
            model_name='col',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 29, 21, 27, 11, 75069), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='table',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 29, 21, 27, 11, 70065), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='value',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 29, 21, 27, 11, 76069), verbose_name='更新时间'),
        ),
    ]
