# Generated by Django 3.2.6 on 2021-08-29 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guang', '0011_auto_20210829_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='v1',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v10',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v100',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v11',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v12',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v13',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v14',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v15',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v16',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v17',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v18',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v19',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v2',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v20',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v21',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v22',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v23',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v24',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v25',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v26',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v27',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v28',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v29',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v3',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v30',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v31',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v32',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v33',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v34',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v35',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v36',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v37',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v38',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v39',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v4',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v40',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v41',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v42',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v43',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v44',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v45',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v46',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v47',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v48',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v49',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v5',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v50',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v51',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v52',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v53',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v54',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v55',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v56',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v57',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v58',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v59',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v6',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v60',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v61',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v62',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v63',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v64',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v65',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v66',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v67',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v68',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v69',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v7',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v70',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v71',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v72',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v73',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v74',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v75',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v76',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v77',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v78',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v79',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v8',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v80',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v81',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v82',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v83',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v84',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v85',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v86',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v87',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v88',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v89',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v9',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v90',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v91',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v92',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v93',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v94',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v95',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v96',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v97',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v98',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AddField(
            model_name='value',
            name='v99',
            field=models.CharField(default='默认值', max_length=20, verbose_name='数据值'),
        ),
        migrations.AlterField(
            model_name='col',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 29, 21, 50, 13, 923404), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='table',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 29, 21, 50, 13, 918402), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='value',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 29, 21, 50, 13, 924405), verbose_name='更新时间'),
        ),
    ]
